config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'items#index'
  get '/admin/users_count', to: 'admin#users_count'

  resources :items do #, only: %i[index create]
    get :upvote, on: :member
    get :expensive, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  
  has_many :comments, as: :commentable

end

app/models/cart.rb
class Cart < ApplicationRecord

belongs_to :user, optional: true
# has_and_belongs_to_many :items
has_many :positions
has_many :items, through: :positions

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user         
  belongs_to :commentable, polymorphic: true

end

app/models/image.rb
class Image < ApplicationRecord

  belongs_to :imageable, polymorphic: true#, inverse_of: :imageable
end

app/models/item.rb
class Item < ApplicationRecord

  # has_and_belongs_to_many :carts
  has_many :positions
  has_many :carts, through: :positions
  has_many :comments, as: :commentable
  has_one :image, as: :imageable

  has_and_belongs_to_many :orders

  validates :price, numericality: { greater_than: 0 }#, allow_nil: true }
  validates :name, :description, presence: true

  # after_initialize {p 'initialize'} #Item.new Item.first
  # after_save {p 'save'} #Item.create Item.save
  # after_create {p 'create'}
  # after_update {p 'update'}
  # after_destroy {p 'destroy'} #Item.desrtoy

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :items

  def calculate_total
    write_attribute :total, items.map(&:price).inject(:+)

  end
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :item
  belongs_to :cart

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :admin?
  # layout 'admin'

  def users_count
    @users_count = User.count
    render layout: 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def render_403
    render file: 'public/403.html', status: :forbidden
  end

  def render_404
    render file: 'public/404.html', status: :not_found
  end

  def admin?
    render_403 unless params[:admin]
    # render json: 'Acces denied', status: :forbidden unless params[:admin]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # layout false
  skip_before_action :verify_authenticity_token
  before_action :find_item, only: %i[show edit update destroy upvote]
  # before_action :admin?, only: %i[edit]
  # after_action :show_info, only: %i[index]

  def index
    # @items = Item.all.sort
                       # order('votes_count DESC, price DESC').limit 20
                       # .where('votes_count >= 2 AND price >= 200')
    @items = Item.all.order(:id).includes :image
    @items = @items.where('price >= ?', params[:price_from]) if params[:price_from]
    @items = @items.where('created_at >= ?', 1.day.ago) if params[:today]
    @items = @items.where('votes_count >= ?', params[:votes_from]) if params[:votes_from]
    # http://localhost:3000/items?votes_from=3&price_from=500&today=1
  end

  def new
    @item = Item.new
  end

  # def show
  #   render body: 'Page not found', status: 404 unless @item
  # end

  def create
    @item = Item.create(items_params)
    if @item.persisted?
      flash[:success] = "Item was created"
      redirect_to items_path
    else
      flash.now[:error] = "Please fill all fields correctly"
      render :new
      # json: item.errors, status: :unprocessable_entity
    end
  end
  # def edit
  #   render body: 'Page not found', status: 404 unless @item
  # end

  def update
    if @item.update(items_params)
      flash[:success] = "Item was updated"
      redirect_to item_path
    else
      flash.now[:error] = "Please fill all fields correctly"
      # render json: @item.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @item.destroy.destroyed?
      flash[:success] = "Item was deleted"
      redirect_to items_path
      # render json: { success: true }
    else
      render json: item.errors, status: :unprocessable_entity
    end
  end

  def upvote
    @item.increment! :votes_count
    redirect_to items_path
  end

  def expensive
    @items = Item.where('price > 50')
    render :index
  end

  private

  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless @item
  end

  def show_info
    puts 'Index hello!'
  end

  def items_params
    params.require(:item).permit(:name, :price, :weight, :description, :real)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def urls_to_content(str)
    str.gsub! (%r{https://[^\s<]+}) do |url|
      if url[/(?:png|jpe?g|gif|svg)$/]
        "<img src='#{url}' width='100'; />"
      else
        "<a href='#{url}' target='_blank'>link to info</a>"
      end
    end
    str.html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
<div>
  <h3>Count users: <%= @users_count %> on this site</h3>
</div>

app/views/include/main/_notification.html.erb
<% if notice %>
  <p class="notice alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/items/edit.html.erb
<h2>Edit <%= @item.name %></h2>

<%= form_tag item_path(@item), method: :put do %>
  <%= label_tag :name %>
  <%= text_field_tag :name, @item.name %>
  <%= label_tag :price %>
  <%= text_field_tag :price, @item.price %>
  <%= label_tag :description %>
  <%= text_field_tag :description, @item.description %>
  <%= label_tag :weight %>
  <%= text_field_tag :weight, @item.weight %>
  <%= submit_tag "Update", class: "btn btn-large btn-primary" %>
<% end %>
<%= render partial: 'shared/email' %>

app/views/items/index.html.erb
<h2>All items</h2>

<% if @items.empty? %>
  <h2>No items</h2>
  <%= button_to 'new item', new_item_path, method: :get %>

<% else %>
  <table class="my_table">
    <tr>
      <th>id</th>
      <th>name</th>
      <th>price</th>
      <th>description</th>
      <th>weight</th>
      <th>real</th>
      <th>rating</th>
      <th>image</th>

      <th>delete</th>
    </tr>
    <% @items.map do |item| %>
    <tr data-item_id="<%= item.id %>">
      <th><%= item.id %></th>
      <th><%= link_to item.name, item_path(item) %></th>
      <th><%= item.price %> $</th>
      <th><%= item.description %></th>
      <th><%= item.weight %></th>
      <th><%= item.real %></th>
      <th><%= item.votes_count %><%= link_to '+', upvote_item_path(item) %></th>
      <th><%= !item.image.nil? ? image_tag(item.image.file, width: '30px', height: '30px') : 'no img' %></th>

      <th><%= button_to 'delete', item_path(item), method: :delete, class: "deleteAction" %></th>
    </tr>
    <% end %>
  </table>

    <%= button_to 'new item', new_item_path, method: :get %>
    <%= button_to 'expensive', expensive_items_path, method: :get %>
    <%= button_to 'All items', items_path, method: :get %>
    <%= button_to 'Admin panel', admin_users_count_path, method: :get %>

<% end %>
<%= render partial: 'shared/email' %>

app/views/items/new.html.erb
<h2>Create New Item</h2>

<%= simple_form_for @item do |f| %>
  <%= f.input :name, input_html: { class: "form-control" } %>
  <%= f.input :price, input_html: { class: "form-control" },required: true  %>
  <%= f.input :description, label: t("item.description"), input_html: { class: "form-control" } %>
  <%= f.input  :weight, input_html: { class: "form-control" } %>

  <%= f.button :submit, class: "btn btn-large btn-primary" %>
<% end %>
<%= render partial: 'shared/email' %>

app/views/items/show.html.erb
<h2>Show</h2>

<h4><%= @item.name.upcase %></h4>

<ul>
  <li>Price: <%= @item.price %>$</li>
  <li>description: <%=urls_to_content(@item.description) %></li>
  <li>link: <%=urls_to_content("https://www.youtube.com/watch?v=_JZJ2G5t2vY&list=PL9Gk1O6XmsoZY7AuimEEhAbCMnmW2eA3Q&index=25") %></li>
  <li>weight: <%= @item.weight %></li>
  <li>real: <%= @item.real %></li>
</ul>

<%= button_to "Edit #{@item.name}", edit_item_path, method: :get %>
<%= button_to "Delete #{@item.name}", item_path(@item), method: :delete %>
<%= button_to "All Items", items_path, method: :get %>
<%= render partial: 'shared/email' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Admin Panel</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('5.jpg') %>
  </head>

  <body>
    <%= render 'include/auth/auth_header' %>
    <div class="container">
      <h1>Rails Course</h1>
      <!-- <p style="color: #B00100"><%= flash[:error] %></p>
      <p style="color: green"><%= flash[:success] %></p> -->
      <%= render 'include/main/notification' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_email.html.erb
<div class="email">
  <h3>По всем вопросам пишите на почту</h3>

  <%= mail_to 'vitaliy.cherednichenko113@gmail.com' do %>
    <p>vitaliy.cherednichenko113@gmail.com</p>
  <% end %>
</div>